Repository CA-G12/Quiz-App-Team13, pull requests merged in 2022-07, with the labels that each got.

#11 Create header for homepage and question page
  css/index.css
  css/question.css
  html/question.html
  index.html
Labels: waiting-review

#12 Create description box for homepage
  css/index.css
  index.html
Labels: Approved

#14 Create question structure
  css/index.css
  css/question.css
  html/question.html
  index.html
Labels: Approved

#15 9 create gameplay form
  css/question.css
  html/question.html
Labels: Approved

#16 13-add-initGame-and-displayQuestions-Function
  css/question.css
  html/question.html
  js/index.js
  js/question.js
Labels: Approved

#17 6 create leaderboard box
  css/index.css
  index.html
Labels: Approved

#18 7 create username input
  css/index.css
  index.html
Labels: waiting-review

#19 added username validation and users object
  html/question.html
  index.html
  js/index.js
  js/question.js
Labels: waiting-review, Approved

#22 create score section
  css/question.css
  html/question.html
Labels: waiting-review

#23 Add score result at the end of the quiz
  css/question.css
  html/question.html
  index.html
  js/index.js
  js/question.js
Labels: Approved

#25 24 create reset go back buttons
  css/index.css
  css/question.css
  html/question.html
  index.html
  js/index.js
  js/question.js
Labels: waiting-review

#27 Update Readme File
  README.md
Labels: waiting-review
